### ISSUE TITLE
R Compilation Error: Error in system(cmd, intern = !verbose) : 'D:/Program' not found

### ISSUE THREAD

**Issue by rdefaccio** [facebook/prophet#1433]
Hi, I'm trying to get prophet setup and running and am running into this error when calling the prophet function for the first time on some data:

> Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
Compiling model (this will take a few minutes...)
If this is the first time fitting a model since package install, this is normal. You should not see this message more than once after install.
Writing model to: C:/Users/vhapugDefacR/R/Library/prophet/libs/x64
Compiling using binary: D:/Program Files/R/R-3.6.3/bin/x64
Error in system(cmd, intern = !verbose) : 'D:/Program' not found
Error in sink(type = "output") : invalid connection

I'm on R version 3.6.3
Working in RStudio version 1.2.5033
In Windows Server 2012 R2 Standard

Rtools seems to be installed and working:
> find_rtools()
[1] TRUE

> pkgbuild::has_build_tools(debug = TRUE)

I've seen some reference to an issue with file paths having spaces in them, could that be the problem?
Also, I do not have administrator privileges so re-installing R or Rtools is not something I can do.

**Comment by bletham** [comment]
Yeah the issue definitely is in the space.
It looks like this should fix it for now:
https://discourse.mc-stan.org/t/newbie-installation-problem/1755/2

Let me know if that doesn't work. We're working on making some improvements to the R build process for the next version so hopefully this will work "out-of-the-box" then.

**Comment by rdefaccio** [comment]
I was able to solve this issue by setting up an instance of R in its own directory right on the main drive then and installed Prophet/rstan/etc... into a library that was also in that directory. I would run the following prior to loading the libraries:

setwd("project_directory")
Sys.setenv(R_HOME = 'D:/R/R-3.6.3')
.libPaths(c('D:/R/R-3.6.3/Library', .libPaths()))
library(prophet)

I can see how your method is probably more straightforward though.
Thanks for the help!
