### ISSUE TITLE
Cannot install prophet.

### ISSUE THREAD

**Issue by nipnipj** [facebook/prophet#2067]
I Cannot install prophet through `install.packages("prophet")`. The following error shows up
```
make: *** [/usr/lib/R/etc/Makeconf:175: stanExports_prophet.o] Error 1
ERROR: compilation failed for package ‘prophet’
```

**Comment by nipnipj** [comment]
The installations work with an older version of rstan, `2.21.2`.

**Comment by tcuongd** [comment]
Thanks for raising this -- we haven't tested compilation from source with the new rstan 2.26 yet. I'm guessing you're on Linux?
