### ISSUE TITLE
AttributeError 'Prophet' object has no attribute 'stan_backend'

### ISSUE THREAD

**Issue by harupy** [facebook/prophet#2697]
**Reproduction**:

```bash
# Fails with cmdstanpy 1.3.0 (latest)
uv run --with 'cmdstanpy' --with 'prophet' python -c 'from prophet import Prophet; m = Prophet()'

# Works with cmdstanpy < 1.3.0
uv run --with 'cmdstanpy<1.3.0' --with 'prophet' python -c 'from prophet import Prophet; m = Prophet()'
```

**Error**:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File
"/Users/foo/.cache/uv/archive-v0/p7y7cYAwrjR2_DTmw9njj/lib/python3.10/site-packages/prophet/forecaster.py", line
 158, in __init__
    self._load_stan_backend(stan_backend)
  File 
"/Users/foo/.cache/uv/archive-v0/p7y7cYAwrjR2_DTmw9njj/lib/python3.10/site-packages/prophet/forecaster.py", line
 171, in _load_stan_backend
    logger.debug("Loaded stan backend: %s", self.stan_backend.get_type())
AttributeError: 'Prophet' object has no attribute 'stan_backend'
```

**Environment**: Prophet 1.2.0, Python 3.10+

**Comment by GuyLoops** [comment]
Also have the same issue.
It was caused by the `cmdstanpy` update to version 1.3.0 (which is a dependency of this package).
I've added to my `pyproject.toml` this line `cmdstanpy = "==1.2.5"` to lock the version until this issue is resolved.
