### ISSUE TITLE
AttributeError: 'DatetimeIndex' object has no attribute 'weekday_name'

### ISSUE THREAD

**Issue by iplayneon** [facebook/prophet#1304]
model.plot_components(forecast)
It is giving me an attribute error.
pandas.__version__ = '1.0.0'
There is no such method called weekday_name in pandas version 1.0.0

**Comment by bletham** [comment]
Thanks for raising this! It looks like this is a change in pandas 1.0.0, which was released yesterday. We'll have to fix this, but in a backwards compatible way that still works with pandas 0.23.4 (the current min requirement).

**Comment by dhernandezgt** [comment]
it happens to me too.
pandas           : 1.0.0

**Comment by bletham** [comment]
This was fixed in #1304, so you can also install from github to get an immediate fix.

**Comment by camiloromers** [comment]
When you install with conda, the issue still persists.

**Comment by luxoracle** [comment]
> When you install it with conda, the issue still persists.

Indeed, it seems that the 'conda install' method fails to create a proper env for prophet.

**Comment by ghuname** [comment]
Is there a solution for conda install?

**Comment by camiloromers** [comment]
@ghuname what I did is downgrade panda version to pandas==0.25.3 and then I works without problems.

**Comment by bletham** [comment]
As of yesterday, the fix has been pushed to both PyPI and conda forge in the latest version (0.6). So fbprophet==0.6 will work with pandas>=1.0.0, and you shouldn't see this error after upgrading.

If you do see this error, please make sure that you're using the latest version (0.6):
```
import fbprophet
print(fbprophet.__version__)
```

**Comment by aylinjr** [comment]
I am using pandas : 1.0.3
I fixed this problem by replacing the weekday_name to weekday in plot.py file line#288.
I hope this helps.

**Comment by AVplusTV** [comment]
I use in pd version 1.1.3 - **day_name()**  instead **weekday_name**

**Comment by Laminf2ray** [comment]
I used in pd version 1.4.2 **day_name()** to display weekday_name and **month_name()** for months name
